sudo: false
language: c

deploy:
  provider: s3
  access_key_id: AKIAI5DCW74VHQYKQPAA
  secret_access_key:
    secure: jV7LhIXkrYZFGiaHtOGRu4FJau8xtbmflf4CNR2hfxTwUTIMKwEG9JMrZREFTHg3UK/RjlKiA3nIkKSbMZ6raCA4nLfAfJVJxr8ku7ZvSzVAFprcg1y98k87tdQzO5aF/BdfMdoz+SxcXynx02veTk9baeHvUn672Fuhil2Jc+U=
  bucket: stackage-travis
  acl: public_read
  skip_cleanup: true
  local_dir: to-travis
  upload-dir: stackage-curator
  on:
    repo: fpco/stackage-curator
    branch: master

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- mkdir -p to-travis
- stack --no-terminal test --install-ghc --copy-bins --local-bin-path to-travis
- bzip2 to-travis/stackage-curator

cache:
  directories:
  - $HOME/.stack
