resolver: lts-8.12
packages:
- .
- location: https://github.com/snoyberg/cabal/archive/19e43a8d767dbb43fa14ba373ba09429bbb73355.zip
  extra-dep: true
  subdirs:
  - Cabal

ghc-options:
  Cabal: "-O2"
